// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:flutter_auth_app/services/hive/hive_adapters.dart';
import 'package:hive_ce/hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(UserModelAdapter());
  }
}
